name: CI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - run: yarn test
