name: CI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - run: yarn test
