name: CI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: openrndr/setup-opengl@v1.1
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - run: xvfb-run -s "-ac -screen 0 1280x1024x24" yarn test
